// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const adminDeleteEvent = `-- name: AdminDeleteEvent :exec
DELETE FROM events WHERE id = ?
`

func (q *Queries) AdminDeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, adminDeleteEvent, id)
	return err
}

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
  user_id,
  title,
  owner_name,
  description,
  location,
  start_time,
  image_url,
  price
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, title, owner_name, description, location, start_time, image_url, price, created_at, updated_at
`

type CreateEventParams struct {
	UserID      int64     `json:"user_id"`
	Title       string    `json:"title"`
	OwnerName   string    `json:"owner_name"`
	Description string    `json:"description"`
	Location    string    `json:"location"`
	StartTime   time.Time `json:"start_time"`
	ImageUrl    string    `json:"image_url"`
	Price       float64   `json:"price"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.UserID,
		arg.Title,
		arg.OwnerName,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.ImageUrl,
		arg.Price,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.OwnerName,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.ImageUrl,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = ? AND user_id = ?
`

type DeleteEventParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, arg.ID, arg.UserID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, user_id, title, owner_name, description, location, start_time, image_url, price, created_at, updated_at FROM events WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.OwnerName,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.ImageUrl,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventWithOwner = `-- name: GetEventWithOwner :one
SELECT
  e.id, e.user_id, e.title, e.owner_name, e.description, e.location, e.start_time, e.image_url, e.price, e.created_at, e.updated_at,
  u.username AS owner_username,
  u.email AS owner_email
FROM events e
JOIN users u ON u.id = e.user_id
WHERE e.id = ?
`

type GetEventWithOwnerRow struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"user_id"`
	Title         string    `json:"title"`
	OwnerName     string    `json:"owner_name"`
	Description   string    `json:"description"`
	Location      string    `json:"location"`
	StartTime     time.Time `json:"start_time"`
	ImageUrl      string    `json:"image_url"`
	Price         float64   `json:"price"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	OwnerUsername string    `json:"owner_username"`
	OwnerEmail    string    `json:"owner_email"`
}

func (q *Queries) GetEventWithOwner(ctx context.Context, id int64) (GetEventWithOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getEventWithOwner, id)
	var i GetEventWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.OwnerName,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.ImageUrl,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUsername,
		&i.OwnerEmail,
	)
	return i, err
}

const getUserEvents = `-- name: GetUserEvents :many
SELECT id, user_id, title, owner_name, description, location, start_time, image_url, price, created_at, updated_at FROM events WHERE user_id = ? ORDER BY start_time
`

func (q *Queries) GetUserEvents(ctx context.Context, userID int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getUserEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.OwnerName,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.ImageUrl,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEventsWithStats = `-- name: GetUserEventsWithStats :many
SELECT
  e.id, e.user_id, e.title, e.owner_name, e.description, e.location, e.start_time, e.image_url, e.price, e.created_at, e.updated_at,
  COUNT(t.id) AS tickets_count,
  COUNT(DISTINCT t.user_id) AS unique_users_count,
  COALESCE(SUM(t.price), 0) AS revenue
FROM events e
LEFT JOIN tickets t ON t.event_id = e.id
WHERE e.user_id = ?
GROUP BY e.id
ORDER BY e.start_time DESC
`

type GetUserEventsWithStatsRow struct {
	ID               int64       `json:"id"`
	UserID           int64       `json:"user_id"`
	Title            string      `json:"title"`
	OwnerName        string      `json:"owner_name"`
	Description      string      `json:"description"`
	Location         string      `json:"location"`
	StartTime        time.Time   `json:"start_time"`
	ImageUrl         string      `json:"image_url"`
	Price            float64     `json:"price"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	TicketsCount     int64       `json:"tickets_count"`
	UniqueUsersCount int64       `json:"unique_users_count"`
	Revenue          interface{} `json:"revenue"`
}

func (q *Queries) GetUserEventsWithStats(ctx context.Context, userID int64) ([]GetUserEventsWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserEventsWithStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserEventsWithStatsRow{}
	for rows.Next() {
		var i GetUserEventsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.OwnerName,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.ImageUrl,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketsCount,
			&i.UniqueUsersCount,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, user_id, title, owner_name, description, location, start_time, image_url, price, created_at, updated_at FROM events ORDER BY start_time
LIMIT ?2 OFFSET ?1
`

type ListEventsParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.OwnerName,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.ImageUrl,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBetween = `-- name: ListEventsBetween :many
SELECT id, user_id, title, owner_name, description, location, start_time, image_url, price, created_at, updated_at FROM events
WHERE start_time BETWEEN ? AND ?
ORDER BY start_time
`

type ListEventsBetweenParams struct {
	FromStartTime time.Time `json:"from_start_time"`
	ToStartTime   time.Time `json:"to_start_time"`
}

func (q *Queries) ListEventsBetween(ctx context.Context, arg ListEventsBetweenParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsBetween, arg.FromStartTime, arg.ToStartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.OwnerName,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.ImageUrl,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsWithTicketStats = `-- name: ListEventsWithTicketStats :many
SELECT
  e.id, e.user_id, e.title, e.owner_name, e.description, e.location, e.start_time, e.image_url, e.price, e.created_at, e.updated_at,
  COUNT(t.id) AS tickets_count,
  COUNT(DISTINCT t.user_id) AS unique_users_count,
  COALESCE(SUM(t.price), 0) AS revenue
FROM events e
LEFT JOIN tickets t ON t.event_id = e.id
GROUP BY e.id
ORDER BY e.start_time
`

type ListEventsWithTicketStatsRow struct {
	ID               int64       `json:"id"`
	UserID           int64       `json:"user_id"`
	Title            string      `json:"title"`
	OwnerName        string      `json:"owner_name"`
	Description      string      `json:"description"`
	Location         string      `json:"location"`
	StartTime        time.Time   `json:"start_time"`
	ImageUrl         string      `json:"image_url"`
	Price            float64     `json:"price"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	TicketsCount     int64       `json:"tickets_count"`
	UniqueUsersCount int64       `json:"unique_users_count"`
	Revenue          interface{} `json:"revenue"`
}

func (q *Queries) ListEventsWithTicketStats(ctx context.Context) ([]ListEventsWithTicketStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsWithTicketStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsWithTicketStatsRow{}
	for rows.Next() {
		var i ListEventsWithTicketStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.OwnerName,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.ImageUrl,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TicketsCount,
			&i.UniqueUsersCount,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchEvent = `-- name: PatchEvent :one
UPDATE events
SET
  title = COALESCE(?1, title),
  owner_name = COALESCE(?2, owner_name),
  description = COALESCE(?3, description),
  location = COALESCE(?4, location),
  start_time = COALESCE(?5, start_time),
  image_url = COALESCE(?6, image_url),
  price = COALESCE(?7, price),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?8 AND user_id = ?9
RETURNING id, user_id, title, owner_name, description, location, start_time, image_url, price, created_at, updated_at
`

type PatchEventParams struct {
	Title       sql.NullString  `json:"title"`
	OwnerName   sql.NullString  `json:"owner_name"`
	Description sql.NullString  `json:"description"`
	Location    sql.NullString  `json:"location"`
	StartTime   sql.NullTime    `json:"start_time"`
	ImageUrl    sql.NullString  `json:"image_url"`
	Price       sql.NullFloat64 `json:"price"`
	ID          int64           `json:"id"`
	UserID      int64           `json:"user_id"`
}

func (q *Queries) PatchEvent(ctx context.Context, arg PatchEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, patchEvent,
		arg.Title,
		arg.OwnerName,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.ImageUrl,
		arg.Price,
		arg.ID,
		arg.UserID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.OwnerName,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.ImageUrl,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchEvents = `-- name: SearchEvents :many
SELECT id, user_id, title, owner_name, description, location, start_time, image_url, price, created_at, updated_at FROM events
WHERE title LIKE ? OR location LIKE ?
ORDER BY start_time
LIMIT ? OFFSET ?
`

type SearchEventsParams struct {
	Title    string `json:"title"`
	Location string `json:"location"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, searchEvents,
		arg.Title,
		arg.Location,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.OwnerName,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.ImageUrl,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
