// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Title       string    `json:"title"`
	OwnerName   string    `json:"owner_name"`
	Description string    `json:"description"`
	Location    string    `json:"location"`
	StartTime   time.Time `json:"start_time"`
	ImageUrl    string    `json:"image_url"`
	Price       float64   `json:"price"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RequestSession struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	SessionTokenHash []byte         `json:"session_token_hash"`
	IpAddress        sql.NullString `json:"ip_address"`
	UserAgent        sql.NullString `json:"user_agent"`
	ExpiresAt        time.Time      `json:"expires_at"`
	LastSeenAt       sql.NullTime   `json:"last_seen_at"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
}

type Ticket struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	EventID   int64     `json:"event_id"`
	Name      string    `json:"name"`
	Signature string    `json:"signature"`
	Price     float64   `json:"price"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Token struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	TokenHash []byte       `json:"token_hash"`
	Expiry    time.Time    `json:"expiry"`
	Scope     string       `json:"scope"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transaction struct {
	ID            int64         `json:"id"`
	UserID        int64         `json:"user_id"`
	EventID       int64         `json:"event_id"`
	TicketID      sql.NullInt64 `json:"ticket_id"`
	TransactionID string        `json:"transaction_id"`
	Amount        float64       `json:"amount"`
	CardLast4     string        `json:"card_last4"`
	Status        string        `json:"status"`
	CreatedAt     time.Time     `json:"created_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Password  string         `json:"password"`
	Email     string         `json:"email"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
