// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AdminDeleteEvent(ctx context.Context, id int64) error
	AdminDeleteTicket(ctx context.Context, id int64) error
	BatchGetUsers(ctx context.Context) ([]BatchGetUsersRow, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	CountEvents(ctx context.Context) (int64, error)
	CountTickets(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	// ==================== Token CRUD ====================
	CreateToken(ctx context.Context, arg CreateTokenParams) (CreateTokenRow, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	// ==================== User CRUD ====================
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAllTokensForUser(ctx context.Context, userID int64) error
	DeleteEvent(ctx context.Context, arg DeleteEventParams) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteTicket(ctx context.Context, arg DeleteTicketParams) error
	DeleteToken(ctx context.Context, id int64) error
	DeleteTokenByHash(ctx context.Context, tokenHash []byte) error
	DeleteTokensByScope(ctx context.Context, arg DeleteTokensByScopeParams) error
	DeleteUser(ctx context.Context, id int64) error
	EmailExists(ctx context.Context, email string) (int64, error)
	GetActiveUsers(ctx context.Context, arg GetActiveUsersParams) ([]GetActiveUsersRow, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetEventTickets(ctx context.Context, eventID int64) ([]Ticket, error)
	GetEventWithOwner(ctx context.Context, id int64) (GetEventWithOwnerRow, error)
	GetTicket(ctx context.Context, id int64) (Ticket, error)
	GetTicketDetailed(ctx context.Context, id int64) (GetTicketDetailedRow, error)
	GetTokenByHash(ctx context.Context, tokenHash []byte) (GetTokenByHashRow, error)
	GetTokenByID(ctx context.Context, id int64) (GetTokenByIDRow, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetTransactionByTxnID(ctx context.Context, transactionID string) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByTokenHash(ctx context.Context, arg GetUserByTokenHashParams) (GetUserByTokenHashRow, error)
	GetUserByTokenHashWithToken(ctx context.Context, tokenHash []byte) (GetUserByTokenHashWithTokenRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (GetUserByUsernameOrEmailRow, error)
	GetUserEvents(ctx context.Context, userID int64) ([]Event, error)
	GetUserEventsWithStats(ctx context.Context, userID int64) ([]GetUserEventsWithStatsRow, error)
	GetUserTickets(ctx context.Context, userID int64) ([]Ticket, error)
	GetUserTicketsWithEvent(ctx context.Context, userID int64) ([]GetUserTicketsWithEventRow, error)
	GetUserTransactions(ctx context.Context, userID int64) ([]GetUserTransactionsRow, error)
	GetUserWithTokens(ctx context.Context, id int64) ([]GetUserWithTokensRow, error)
	GetValidTokenByUserAndScope(ctx context.Context, arg GetValidTokenByUserAndScopeParams) (GetValidTokenByUserAndScopeRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListEventsBetween(ctx context.Context, arg ListEventsBetweenParams) ([]Event, error)
	ListEventsWithTicketStats(ctx context.Context) ([]ListEventsWithTicketStatsRow, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error)
	ListTicketsBetween(ctx context.Context, arg ListTicketsBetweenParams) ([]Ticket, error)
	ListTicketsByStatusForEvent(ctx context.Context, arg ListTicketsByStatusForEventParams) ([]Ticket, error)
	ListTicketsForEventWithUser(ctx context.Context, eventID int64) ([]ListTicketsForEventWithUserRow, error)
	ListTokensForUser(ctx context.Context, userID int64) ([]ListTokensForUserRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	PatchEvent(ctx context.Context, arg PatchEventParams) (Event, error)
	PatchTicket(ctx context.Context, arg PatchTicketParams) (Ticket, error)
	PatchUser(ctx context.Context, arg PatchUserParams) (PatchUserRow, error)
	RestoreUser(ctx context.Context, id int64) error
	SearchEvents(ctx context.Context, arg SearchEventsParams) ([]Event, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error
	SoftDeleteUser(ctx context.Context) error
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateTransactionTicketID(ctx context.Context, arg UpdateTransactionTicketIDParams) error
	// ==================== Additional Useful Queries ====================
	UserExists(ctx context.Context, id int64) (int64, error)
	UsernameExists(ctx context.Context, username string) (int64, error)
}

var _ Querier = (*Queries)(nil)
