// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request_sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRequestSession = `-- name: CreateRequestSession :one
INSERT INTO request_sessions (
    user_id,
    session_token_hash,
    ip_address,
    user_agent,
    expires_at
)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, user_id, session_token_hash, ip_address, user_agent, expires_at, last_seen_at, created_at, revoked_at
`

type CreateRequestSessionParams struct {
	UserID           int64          `json:"user_id"`
	SessionTokenHash []byte         `json:"session_token_hash"`
	IpAddress        sql.NullString `json:"ip_address"`
	UserAgent        sql.NullString `json:"user_agent"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

func (q *Queries) CreateRequestSession(ctx context.Context, arg CreateRequestSessionParams) (RequestSession, error) {
	row := q.db.QueryRowContext(ctx, createRequestSession,
		arg.UserID,
		arg.SessionTokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i RequestSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredOrRevokedRequestSessions = `-- name: DeleteExpiredOrRevokedRequestSessions :exec
DELETE FROM request_sessions
WHERE expires_at < datetime('now')
   OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredOrRevokedRequestSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOrRevokedRequestSessions)
	return err
}

const getRequestSessionByTokenHash = `-- name: GetRequestSessionByTokenHash :one
SELECT id, user_id, session_token_hash, ip_address, user_agent, expires_at, last_seen_at, created_at, revoked_at
FROM request_sessions
WHERE session_token_hash = ?1
`

func (q *Queries) GetRequestSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) (RequestSession, error) {
	row := q.db.QueryRowContext(ctx, getRequestSessionByTokenHash, sessionTokenHash)
	var i RequestSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveRequestSessionsForUser = `-- name: ListActiveRequestSessionsForUser :many
SELECT id, user_id, session_token_hash, ip_address, user_agent, expires_at, last_seen_at, created_at, revoked_at
FROM request_sessions
WHERE user_id = ?1
  AND revoked_at IS NULL
  AND expires_at > datetime('now')
ORDER BY created_at DESC
`

func (q *Queries) ListActiveRequestSessionsForUser(ctx context.Context, userID int64) ([]RequestSession, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRequestSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestSession{}
	for rows.Next() {
		var i RequestSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionTokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllRequestSessionsForUser = `-- name: RevokeAllRequestSessionsForUser :exec
UPDATE request_sessions
SET revoked_at = datetime('now')
WHERE user_id = ?1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRequestSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, revokeAllRequestSessionsForUser, userID)
	return err
}

const revokeRequestSessionByTokenHash = `-- name: RevokeRequestSessionByTokenHash :exec
UPDATE request_sessions
SET revoked_at = datetime('now')
WHERE session_token_hash = ?1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRequestSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, revokeRequestSessionByTokenHash, sessionTokenHash)
	return err
}

const touchRequestSession = `-- name: TouchRequestSession :exec
UPDATE request_sessions
SET last_seen_at = datetime('now')
WHERE session_token_hash = ?1
  AND revoked_at IS NULL
  AND expires_at > datetime('now')
`

func (q *Queries) TouchRequestSession(ctx context.Context, sessionTokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, touchRequestSession, sessionTokenHash)
	return err
}
