// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const adminDeleteTicket = `-- name: AdminDeleteTicket :exec
DELETE FROM tickets WHERE id = ?
`

func (q *Queries) AdminDeleteTicket(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, adminDeleteTicket, id)
	return err
}

const countTickets = `-- name: CountTickets :one
SELECT COUNT(*) FROM tickets
`

func (q *Queries) CountTickets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTickets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
  user_id,
  event_id,
  name,
  signature,
  price,
  status
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, event_id, name, signature, price, status, created_at, updated_at
`

type CreateTicketParams struct {
	UserID    int64   `json:"user_id"`
	EventID   int64   `json:"event_id"`
	Name      string  `json:"name"`
	Signature string  `json:"signature"`
	Price     float64 `json:"price"`
	Status    string  `json:"status"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.UserID,
		arg.EventID,
		arg.Name,
		arg.Signature,
		arg.Price,
		arg.Status,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Name,
		&i.Signature,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets WHERE id = ? AND user_id = ?
`

type DeleteTicketParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTicket(ctx context.Context, arg DeleteTicketParams) error {
	_, err := q.db.ExecContext(ctx, deleteTicket, arg.ID, arg.UserID)
	return err
}

const getEventTickets = `-- name: GetEventTickets :many
SELECT id, user_id, event_id, name, signature, price, status, created_at, updated_at FROM tickets WHERE event_id = ? ORDER BY created_at
`

func (q *Queries) GetEventTickets(ctx context.Context, eventID int64) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getEventTickets, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Name,
			&i.Signature,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicket = `-- name: GetTicket :one
SELECT id, user_id, event_id, name, signature, price, status, created_at, updated_at FROM tickets WHERE id = ?
`

func (q *Queries) GetTicket(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Name,
		&i.Signature,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketDetailed = `-- name: GetTicketDetailed :one
SELECT
  t.id, t.user_id, t.event_id, t.name, t.signature, t.price, t.status, t.created_at, t.updated_at,
  e.title AS event_title,
  e.start_time AS event_start_time,
  e.image_url AS event_image_url,
  u.username AS user_username,
  u.email AS user_email
FROM tickets t
JOIN events e ON e.id = t.event_id
JOIN users u ON u.id = t.user_id
WHERE t.id = ?
`

type GetTicketDetailedRow struct {
	ID             int64     `json:"id"`
	UserID         int64     `json:"user_id"`
	EventID        int64     `json:"event_id"`
	Name           string    `json:"name"`
	Signature      string    `json:"signature"`
	Price          float64   `json:"price"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	EventTitle     string    `json:"event_title"`
	EventStartTime time.Time `json:"event_start_time"`
	EventImageUrl  string    `json:"event_image_url"`
	UserUsername   string    `json:"user_username"`
	UserEmail      string    `json:"user_email"`
}

func (q *Queries) GetTicketDetailed(ctx context.Context, id int64) (GetTicketDetailedRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketDetailed, id)
	var i GetTicketDetailedRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Name,
		&i.Signature,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventTitle,
		&i.EventStartTime,
		&i.EventImageUrl,
		&i.UserUsername,
		&i.UserEmail,
	)
	return i, err
}

const getUserTickets = `-- name: GetUserTickets :many
SELECT id, user_id, event_id, name, signature, price, status, created_at, updated_at FROM tickets WHERE user_id = ? ORDER BY created_at
`

func (q *Queries) GetUserTickets(ctx context.Context, userID int64) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getUserTickets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Name,
			&i.Signature,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTicketsWithEvent = `-- name: GetUserTicketsWithEvent :many
SELECT
  t.id, t.user_id, t.event_id, t.name, t.signature, t.price, t.status, t.created_at, t.updated_at,
  e.title AS event_title,
  e.image_url AS event_image_url
FROM tickets t
JOIN events e ON e.id = t.event_id
WHERE t.user_id = ?
ORDER BY t.created_at DESC
`

type GetUserTicketsWithEventRow struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"user_id"`
	EventID       int64     `json:"event_id"`
	Name          string    `json:"name"`
	Signature     string    `json:"signature"`
	Price         float64   `json:"price"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	EventTitle    string    `json:"event_title"`
	EventImageUrl string    `json:"event_image_url"`
}

func (q *Queries) GetUserTicketsWithEvent(ctx context.Context, userID int64) ([]GetUserTicketsWithEventRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTicketsWithEvent, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserTicketsWithEventRow{}
	for rows.Next() {
		var i GetUserTicketsWithEventRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Name,
			&i.Signature,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventTitle,
			&i.EventImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, user_id, event_id, name, signature, price, status, created_at, updated_at FROM tickets ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListTicketsParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTickets, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Name,
			&i.Signature,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsBetween = `-- name: ListTicketsBetween :many
SELECT id, user_id, event_id, name, signature, price, status, created_at, updated_at FROM tickets
WHERE created_at BETWEEN ? AND ?
ORDER BY created_at
`

type ListTicketsBetweenParams struct {
	FromCreatedAt time.Time `json:"from_created_at"`
	ToCreatedAt   time.Time `json:"to_created_at"`
}

func (q *Queries) ListTicketsBetween(ctx context.Context, arg ListTicketsBetweenParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsBetween, arg.FromCreatedAt, arg.ToCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Name,
			&i.Signature,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByStatusForEvent = `-- name: ListTicketsByStatusForEvent :many
SELECT id, user_id, event_id, name, signature, price, status, created_at, updated_at FROM tickets
WHERE event_id = ? AND status = ?
ORDER BY created_at
`

type ListTicketsByStatusForEventParams struct {
	EventID int64  `json:"event_id"`
	Status  string `json:"status"`
}

func (q *Queries) ListTicketsByStatusForEvent(ctx context.Context, arg ListTicketsByStatusForEventParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByStatusForEvent, arg.EventID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Name,
			&i.Signature,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsForEventWithUser = `-- name: ListTicketsForEventWithUser :many
SELECT
  t.id, t.user_id, t.event_id, t.name, t.signature, t.price, t.status, t.created_at, t.updated_at,
  u.username AS user_username,
  u.email AS user_email
FROM tickets t
JOIN users u ON u.id = t.user_id
WHERE t.event_id = ?
ORDER BY t.created_at
`

type ListTicketsForEventWithUserRow struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	EventID      int64     `json:"event_id"`
	Name         string    `json:"name"`
	Signature    string    `json:"signature"`
	Price        float64   `json:"price"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	UserUsername string    `json:"user_username"`
	UserEmail    string    `json:"user_email"`
}

func (q *Queries) ListTicketsForEventWithUser(ctx context.Context, eventID int64) ([]ListTicketsForEventWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsForEventWithUser, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsForEventWithUserRow{}
	for rows.Next() {
		var i ListTicketsForEventWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Name,
			&i.Signature,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserUsername,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchTicket = `-- name: PatchTicket :one
UPDATE tickets
SET
  name = COALESCE(?1, name),
  price = COALESCE(?2, price),
  status = COALESCE(?3, status),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?4 AND user_id = ?5
RETURNING id, user_id, event_id, name, signature, price, status, created_at, updated_at
`

type PatchTicketParams struct {
	Name   sql.NullString  `json:"name"`
	Price  sql.NullFloat64 `json:"price"`
	Status sql.NullString  `json:"status"`
	ID     int64           `json:"id"`
	UserID int64           `json:"user_id"`
}

func (q *Queries) PatchTicket(ctx context.Context, arg PatchTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, patchTicket,
		arg.Name,
		arg.Price,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Name,
		&i.Signature,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
