// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createToken = `-- name: CreateToken :one

INSERT INTO tokens (user_id, token_hash, expiry, scope)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, user_id, token_hash, scope, expiry, created_at
`

type CreateTokenParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	Expiry    time.Time `json:"expiry"`
	Scope     string    `json:"scope"`
}

type CreateTokenRow struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	TokenHash []byte       `json:"token_hash"`
	Scope     string       `json:"scope"`
	Expiry    time.Time    `json:"expiry"`
	CreatedAt sql.NullTime `json:"created_at"`
}

// ==================== Token CRUD ====================
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (CreateTokenRow, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.UserID,
		arg.TokenHash,
		arg.Expiry,
		arg.Scope,
	)
	var i CreateTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Scope,
		&i.Expiry,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllTokensForUser = `-- name: DeleteAllTokensForUser :exec
DELETE FROM tokens
WHERE user_id = ?1
`

func (q *Queries) DeleteAllTokensForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllTokensForUser, userID)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM tokens
WHERE expiry < datetime('now')
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTokens)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens
WHERE id = ?1
`

func (q *Queries) DeleteToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteToken, id)
	return err
}

const deleteTokenByHash = `-- name: DeleteTokenByHash :exec
DELETE FROM tokens
WHERE token_hash = ?1
`

func (q *Queries) DeleteTokenByHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteTokenByHash, tokenHash)
	return err
}

const deleteTokensByScope = `-- name: DeleteTokensByScope :exec
DELETE FROM tokens
WHERE user_id = ?1 AND scope = ?2
`

type DeleteTokensByScopeParams struct {
	UserID int64  `json:"user_id"`
	Scope  string `json:"scope"`
}

func (q *Queries) DeleteTokensByScope(ctx context.Context, arg DeleteTokensByScopeParams) error {
	_, err := q.db.ExecContext(ctx, deleteTokensByScope, arg.UserID, arg.Scope)
	return err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, token_hash, scope, expiry, created_at
FROM tokens
WHERE token_hash = ?1
`

type GetTokenByHashRow struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	TokenHash []byte       `json:"token_hash"`
	Scope     string       `json:"scope"`
	Expiry    time.Time    `json:"expiry"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash []byte) (GetTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, tokenHash)
	var i GetTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Scope,
		&i.Expiry,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, user_id, token_hash, scope, expiry, created_at
FROM tokens
WHERE id = ?1
`

type GetTokenByIDRow struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	TokenHash []byte       `json:"token_hash"`
	Scope     string       `json:"scope"`
	Expiry    time.Time    `json:"expiry"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetTokenByID(ctx context.Context, id int64) (GetTokenByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTokenByID, id)
	var i GetTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Scope,
		&i.Expiry,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByTokenHash = `-- name: GetUserByTokenHash :one
SELECT users.id, users.username, users.email, users.password, users.bio,
       users.is_admin, users.created_at, users.updated_at
FROM users
INNER JOIN tokens ON users.id = tokens.user_id
WHERE tokens.token_hash = ?1
  AND tokens.scope = ?2
  AND tokens.expiry > datetime('now')
`

type GetUserByTokenHashParams struct {
	TokenHash []byte `json:"token_hash"`
	Scope     string `json:"scope"`
}

type GetUserByTokenHashRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByTokenHash(ctx context.Context, arg GetUserByTokenHashParams) (GetUserByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByTokenHash, arg.TokenHash, arg.Scope)
	var i GetUserByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Bio,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidTokenByUserAndScope = `-- name: GetValidTokenByUserAndScope :one
SELECT id, user_id, token_hash, scope, expiry, created_at
FROM tokens
WHERE user_id = ?1 
  AND scope = ?2 
  AND expiry > datetime('now')
LIMIT 1
`

type GetValidTokenByUserAndScopeParams struct {
	UserID int64  `json:"user_id"`
	Scope  string `json:"scope"`
}

type GetValidTokenByUserAndScopeRow struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	TokenHash []byte       `json:"token_hash"`
	Scope     string       `json:"scope"`
	Expiry    time.Time    `json:"expiry"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetValidTokenByUserAndScope(ctx context.Context, arg GetValidTokenByUserAndScopeParams) (GetValidTokenByUserAndScopeRow, error) {
	row := q.db.QueryRowContext(ctx, getValidTokenByUserAndScope, arg.UserID, arg.Scope)
	var i GetValidTokenByUserAndScopeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Scope,
		&i.Expiry,
		&i.CreatedAt,
	)
	return i, err
}

const listTokensForUser = `-- name: ListTokensForUser :many
SELECT id, user_id, token_hash, scope, expiry, created_at
FROM tokens
WHERE user_id = ?1
ORDER BY created_at DESC
`

type ListTokensForUserRow struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	TokenHash []byte       `json:"token_hash"`
	Scope     string       `json:"scope"`
	Expiry    time.Time    `json:"expiry"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) ListTokensForUser(ctx context.Context, userID int64) ([]ListTokensForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokensForUserRow{}
	for rows.Next() {
		var i ListTokensForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Scope,
			&i.Expiry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
