// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  user_id,
  event_id,
  ticket_id,
  transaction_id,
  amount,
  card_last4,
  status
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, event_id, ticket_id, transaction_id, amount, card_last4, status, created_at
`

type CreateTransactionParams struct {
	UserID        int64         `json:"user_id"`
	EventID       int64         `json:"event_id"`
	TicketID      sql.NullInt64 `json:"ticket_id"`
	TransactionID string        `json:"transaction_id"`
	Amount        float64       `json:"amount"`
	CardLast4     string        `json:"card_last4"`
	Status        string        `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.EventID,
		arg.TicketID,
		arg.TransactionID,
		arg.Amount,
		arg.CardLast4,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketID,
		&i.TransactionID,
		&i.Amount,
		&i.CardLast4,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, event_id, ticket_id, transaction_id, amount, card_last4, status, created_at FROM transactions WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketID,
		&i.TransactionID,
		&i.Amount,
		&i.CardLast4,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByTxnID = `-- name: GetTransactionByTxnID :one
SELECT id, user_id, event_id, ticket_id, transaction_id, amount, card_last4, status, created_at FROM transactions WHERE transaction_id = ?
`

func (q *Queries) GetTransactionByTxnID(ctx context.Context, transactionID string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByTxnID, transactionID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketID,
		&i.TransactionID,
		&i.Amount,
		&i.CardLast4,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserTransactions = `-- name: GetUserTransactions :many
SELECT
  t.id, t.user_id, t.event_id, t.ticket_id, t.transaction_id, t.amount, t.card_last4, t.status, t.created_at,
  e.title AS event_title
FROM transactions t
JOIN events e ON e.id = t.event_id
WHERE t.user_id = ?
ORDER BY t.created_at DESC
`

type GetUserTransactionsRow struct {
	ID            int64         `json:"id"`
	UserID        int64         `json:"user_id"`
	EventID       int64         `json:"event_id"`
	TicketID      sql.NullInt64 `json:"ticket_id"`
	TransactionID string        `json:"transaction_id"`
	Amount        float64       `json:"amount"`
	CardLast4     string        `json:"card_last4"`
	Status        string        `json:"status"`
	CreatedAt     time.Time     `json:"created_at"`
	EventTitle    string        `json:"event_title"`
}

func (q *Queries) GetUserTransactions(ctx context.Context, userID int64) ([]GetUserTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserTransactionsRow{}
	for rows.Next() {
		var i GetUserTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketID,
			&i.TransactionID,
			&i.Amount,
			&i.CardLast4,
			&i.Status,
			&i.CreatedAt,
			&i.EventTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionTicketID = `-- name: UpdateTransactionTicketID :exec
UPDATE transactions SET ticket_id = ? WHERE id = ?
`

type UpdateTransactionTicketIDParams struct {
	TicketID sql.NullInt64 `json:"ticket_id"`
	ID       int64         `json:"id"`
}

func (q *Queries) UpdateTransactionTicketID(ctx context.Context, arg UpdateTransactionTicketIDParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionTicketID, arg.TicketID, arg.ID)
	return err
}
