// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const batchGetUsers = `-- name: BatchGetUsers :many
SELECT id, username, email, bio, is_admin, created_at, updated_at
FROM users
WHERE id IN (SELECT value FROM json_each(?1))
ORDER BY created_at DESC
`

type BatchGetUsersRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) BatchGetUsers(ctx context.Context) ([]BatchGetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, batchGetUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchGetUsersRow{}
	for rows.Next() {
		var i BatchGetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, email, password, bio)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, username, email, password, bio, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	Username string         `json:"username"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Bio      sql.NullString `json:"bio"`
}

type CreateUserRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

// ==================== User CRUD ====================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Bio,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Bio,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE email = ?1
)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, emailExists, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getActiveUsers = `-- name: GetActiveUsers :many
SELECT id, username, email, bio, created_at, updated_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ?1 OFFSET ?2
`

type GetActiveUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GetActiveUsersRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Bio       sql.NullString `json:"bio"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetActiveUsers(ctx context.Context, arg GetActiveUsersParams) ([]GetActiveUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveUsersRow{}
	for rows.Next() {
		var i GetActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, bio, is_admin, created_at, updated_at
FROM users
WHERE email = ?1
`

type GetUserByEmailRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Bio,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, bio, is_admin, created_at, updated_at
FROM users
WHERE id = ?1
`

type GetUserByIDRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Bio,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTokenHashWithToken = `-- name: GetUserByTokenHashWithToken :one
SELECT 
    u.id, u.username, u.email, u.bio, u.is_admin, u.created_at, u.updated_at,
    t.scope, t.expiry
FROM tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = ?1
`

type GetUserByTokenHashWithTokenRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Scope     string         `json:"scope"`
	Expiry    time.Time      `json:"expiry"`
}

func (q *Queries) GetUserByTokenHashWithToken(ctx context.Context, tokenHash []byte) (GetUserByTokenHashWithTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByTokenHashWithToken, tokenHash)
	var i GetUserByTokenHashWithTokenRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Bio,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.Expiry,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, bio, is_admin, created_at, updated_at
FROM users
WHERE username = ?1
`

type GetUserByUsernameRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Bio,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, email, password, bio, is_admin, created_at, updated_at
FROM users
WHERE username = ?1 OR email = ?2
`

type GetUserByUsernameOrEmailParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type GetUserByUsernameOrEmailRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (GetUserByUsernameOrEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameOrEmail, arg.Username, arg.Email)
	var i GetUserByUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Bio,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithTokens = `-- name: GetUserWithTokens :many
SELECT 
    u.id, u.username, u.email, u.password, u.bio, u.is_admin, u.created_at, u.updated_at,
    t.id as token_id, t.token_hash, t.scope, t.expiry, t.created_at as token_created_at
FROM users u
LEFT JOIN tokens t ON u.id = t.user_id AND t.expiry > datetime('now')
WHERE u.id = ?1
`

type GetUserWithTokensRow struct {
	ID             int64          `json:"id"`
	Username       string         `json:"username"`
	Email          string         `json:"email"`
	Password       string         `json:"password"`
	Bio            sql.NullString `json:"bio"`
	IsAdmin        bool           `json:"is_admin"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	TokenID        sql.NullInt64  `json:"token_id"`
	TokenHash      []byte         `json:"token_hash"`
	Scope          sql.NullString `json:"scope"`
	Expiry         sql.NullTime   `json:"expiry"`
	TokenCreatedAt sql.NullTime   `json:"token_created_at"`
}

func (q *Queries) GetUserWithTokens(ctx context.Context, id int64) ([]GetUserWithTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithTokens, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserWithTokensRow{}
	for rows.Next() {
		var i GetUserWithTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Bio,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TokenID,
			&i.TokenHash,
			&i.Scope,
			&i.Expiry,
			&i.TokenCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password, bio, is_admin, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT ?1 OFFSET ?2
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListUsersRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Bio,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchUser = `-- name: PatchUser :one
UPDATE users
SET 
    username = COALESCE(?1, username),
    email = COALESCE(?2, email),
    password = COALESCE(?3, password),
    bio = COALESCE(?4, bio),
    updated_at = datetime('now')
WHERE id = ?5
RETURNING id, username, email, password, bio, is_admin, created_at, updated_at
`

type PatchUserParams struct {
	Username sql.NullString `json:"username"`
	Email    sql.NullString `json:"email"`
	Password sql.NullString `json:"password"`
	Bio      sql.NullString `json:"bio"`
	ID       int64          `json:"id"`
}

type PatchUserRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) PatchUser(ctx context.Context, arg PatchUserParams) (PatchUserRow, error) {
	row := q.db.QueryRowContext(ctx, patchUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Bio,
		arg.ID,
	)
	var i PatchUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Bio,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET deleted_at = NULL
WHERE id = ?1
`

func (q *Queries) RestoreUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreUser, id)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, password, bio, is_admin, created_at, updated_at
FROM users
WHERE username LIKE '%' || ?1 || '%'
   OR email LIKE '%' || ?1 || '%'
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?3
`

type SearchUsersParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int64          `json:"limit"`
	Offset  int64          `json:"offset"`
}

type SearchUsersRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Bio,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users SET is_admin = ?1, updated_at = datetime('now') WHERE id = ?2
`

type SetUserAdminParams struct {
	IsAdmin bool  `json:"is_admin"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.ExecContext(ctx, setUserAdmin, arg.IsAdmin, arg.ID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at DATETIME
`

func (q *Queries) SoftDeleteUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser)
	return err
}

const updateEmail = `-- name: UpdateEmail :exec
UPDATE users
SET email = ?1, updated_at = datetime('now')
WHERE id = ?2
`

type UpdateEmailParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateEmail, arg.Email, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password = ?1, updated_at = datetime('now')
WHERE id = ?2
`

type UpdatePasswordParams struct {
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Password, arg.ID)
	return err
}

const userExists = `-- name: UserExists :one

SELECT EXISTS(
    SELECT 1 FROM users WHERE id = ?1
)
`

// ==================== Additional Useful Queries ====================
func (q *Queries) UserExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE username = ?1
)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, usernameExists, username)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
